### checking if the server is live

GET http://localhost:8000/


 # ============== USER API

### POST new user
POST  http://localhost:8000/api/v1/user
Content-Type: application/json

{
    "name":"Monday",
    "email":"monday.gmail.com",
    "pin": 1234
}

### Get single user
GET http://localhost:8000/api/v1/user
Content-Type: application/json
